version: "3.8"

services:
  app:
    container_name: app
    build: .
    command: go run main.go
    logging:
      driver: json-file
    ports:
      - "443:8080"

  db:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"