version: "3.8"

services:
  app:
    container_name: app
    build: .
    command: go run cmd/server/main.go
    logging:
      driver: json-file
    ports:
      - "443:8080"
    volumes:
      - mongodata:/data/db

  db-prod:
    image: mongo
    container_name: mongodb
    restart: always

  db-dev:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"

volumes:
  mongodata:
