### 1
POST localhost:8080/position
Content-Type: application/json

{
  "ticker": "MGNT",
  "type": "long",
  "target_price": "8000",
  "deadline": "2024-04-28T14:41:30+05:00"
}


### 2
GET localhost:8080/position/0