AccountId: ""
APIToken: "t.nONxSXhec_JLvcjuJW8uv_1TjxEfKc5MjQc6qf14ad6dvoVbTd-FRpkI7I1-ophrYmbMqUpniUOpCi2yVjuHsQ"
EndPoint: sandbox-invest-public-api.tinkoff.ru:443
AppName: invest-api-go-sdk
DisableResourceExhaustedRetry: false
DisableAllRetry: false
MaxRetries: 3