### 1
POST localhost/api/v1/position

{
  "name": "Магнит темка жоская ребят!!!!",
  "createdBy": "MK",
  "ticker": "MGNT",
  "type": "long",
  "targetPrice": 11000.000,
  "lots": [
   {
    "amount": 300,
    "price": 7741.0
    }
  ],
  "Deadline": "2024 May 30"
}


### 2
GET localhost/api/v1/position/MK/magnit-temka-zhoskaia-rebiat
