### 1
POST localhost/api/idea

{
"Positions":[{"Ticker":"MGNT","Kind":0,"InstrumentType":1,"RelAmount":100,"StartPrice":4000,"TargetPrice":800,"FixedProfitP":0,"Log":null}],
"Deadline":"2024-03-28T22:38:42.70871+05:00",
"Log":null
}


### 2
GET localhost/api/idea/0


### 3
PATCH localhost/api/idea/1/deadline

{"Time":"2024-03-28T22:54:38.63347+05:00","NewDeadline":"2024-03-28T22:54:38.63347+05:00"}


### 4
GET localhost/api/idea/1/position/1


### 5
PATCH localhost/api/idea/1/position/1/target

{"Time":"2024-03-28T22:54:38.63347+05:00","NewTargetPrice":1000}


### 6
PATCH localhost/api/idea/0/position/0/amount

{"Time":"2024-03-28T22:54:38.63347+05:00", "Delta":-50, "Price":8000}
